# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/dell/Desktop/PFA_PROJET_FINAL/affichage-fir/affichage-fir.srcs/sources_1/bd/design_1/ip/design_1_matlab_fir_0_0/design_1_matlab_fir_0_0.xci
# IP: The module: 'design_1_matlab_fir_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: c:/Users/dell/Desktop/PFA_PROJET_FINAL/affichage-fir/affichage-fir.srcs/sources_1/bd/design_1/ip/design_1_matlab_fir_0_0/matlab_fir_c_addsub_v12_0_i0/matlab_fir_c_addsub_v12_0_i0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==matlab_fir_c_addsub_v12_0_i0 || ORIG_REF_NAME==matlab_fir_c_addsub_v12_0_i0} -quiet] -quiet

# IP: c:/Users/dell/Desktop/PFA_PROJET_FINAL/affichage-fir/affichage-fir.srcs/sources_1/bd/design_1/ip/design_1_matlab_fir_0_0/matlab_fir_c_addsub_v12_0_i1/matlab_fir_c_addsub_v12_0_i1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==matlab_fir_c_addsub_v12_0_i1 || ORIG_REF_NAME==matlab_fir_c_addsub_v12_0_i1} -quiet] -quiet

# IP: c:/Users/dell/Desktop/PFA_PROJET_FINAL/affichage-fir/affichage-fir.srcs/sources_1/bd/design_1/ip/design_1_matlab_fir_0_0/matlab_fir_mult_gen_v12_0_i0/matlab_fir_mult_gen_v12_0_i0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==matlab_fir_mult_gen_v12_0_i0 || ORIG_REF_NAME==matlab_fir_mult_gen_v12_0_i0} -quiet] -quiet

# XDC: c:/Users/dell/Desktop/PFA_PROJET_FINAL/affichage-fir/affichage-fir.srcs/sources_1/bd/design_1/ip/design_1_matlab_fir_0_0/constrs/matlab_fir.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_matlab_fir_0_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: c:/Users/dell/Desktop/PFA_PROJET_FINAL/affichage-fir/affichage-fir.srcs/sources_1/bd/design_1/ip/design_1_matlab_fir_0_0/design_1_matlab_fir_0_0.xci
# IP: The module: 'design_1_matlab_fir_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: c:/Users/dell/Desktop/PFA_PROJET_FINAL/affichage-fir/affichage-fir.srcs/sources_1/bd/design_1/ip/design_1_matlab_fir_0_0/matlab_fir_c_addsub_v12_0_i0/matlab_fir_c_addsub_v12_0_i0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==matlab_fir_c_addsub_v12_0_i0 || ORIG_REF_NAME==matlab_fir_c_addsub_v12_0_i0} -quiet] -quiet

# IP: c:/Users/dell/Desktop/PFA_PROJET_FINAL/affichage-fir/affichage-fir.srcs/sources_1/bd/design_1/ip/design_1_matlab_fir_0_0/matlab_fir_c_addsub_v12_0_i1/matlab_fir_c_addsub_v12_0_i1.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==matlab_fir_c_addsub_v12_0_i1 || ORIG_REF_NAME==matlab_fir_c_addsub_v12_0_i1} -quiet] -quiet

# IP: c:/Users/dell/Desktop/PFA_PROJET_FINAL/affichage-fir/affichage-fir.srcs/sources_1/bd/design_1/ip/design_1_matlab_fir_0_0/matlab_fir_mult_gen_v12_0_i0/matlab_fir_mult_gen_v12_0_i0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==matlab_fir_mult_gen_v12_0_i0 || ORIG_REF_NAME==matlab_fir_mult_gen_v12_0_i0} -quiet] -quiet

# XDC: c:/Users/dell/Desktop/PFA_PROJET_FINAL/affichage-fir/affichage-fir.srcs/sources_1/bd/design_1/ip/design_1_matlab_fir_0_0/constrs/matlab_fir.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_matlab_fir_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
