# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/sysgen/cic_clock.xdc

# XDC: imports/sysgen/cic.xdc

# Block Designs: bd/cic_bd/cic_bd.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==cic_bd || ORIG_REF_NAME==cic_bd} -quiet] -quiet

# IP: bd/cic_bd/ip/cic_bd_cic_1_0/cic_bd_cic_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==cic_bd_cic_1_0 || ORIG_REF_NAME==cic_bd_cic_1_0} -quiet] -quiet

# IP: bd/cic_bd/ip/cic_bd_processing_system_1_0/cic_bd_processing_system_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==cic_bd_processing_system_1_0 || ORIG_REF_NAME==cic_bd_processing_system_1_0} -quiet] -quiet

# IP: bd/cic_bd/ip/cic_bd_auto_pc_0/cic_bd_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==cic_bd_auto_pc_0 || ORIG_REF_NAME==cic_bd_auto_pc_0} -quiet] -quiet

# IP: bd/cic_bd/ip/cic_bd_processing_system_1_axi_periph_0/cic_bd_processing_system_1_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==cic_bd_processing_system_1_axi_periph_0 || ORIG_REF_NAME==cic_bd_processing_system_1_axi_periph_0} -quiet] -quiet

# IP: bd/cic_bd/ip/cic_bd_rst_processing_system_1_50M_0/cic_bd_rst_processing_system_1_50M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==cic_bd_rst_processing_system_1_50M_0 || ORIG_REF_NAME==cic_bd_rst_processing_system_1_50M_0} -quiet] -quiet

# XDC: bd/cic_bd/cic_bd_ooc.xdc
