# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/dell/Desktop/PFA_PROJET_FINAL/project_FIR-final/project_FIR-final.srcs/sources_1/ip/lab1_4_2_sol_0/lab1_4_2_sol_0.xci
# IP: The module: 'lab1_4_2_sol_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: c:/Users/dell/Desktop/PFA_PROJET_FINAL/project_FIR-final/project_FIR-final.srcs/sources_1/ip/lab1_4_2_sol_0/lab1_4_2_sol_floating_point_v7_1_i0/lab1_4_2_sol_floating_point_v7_1_i0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==lab1_4_2_sol_floating_point_v7_1_i0 || ORIG_REF_NAME==lab1_4_2_sol_floating_point_v7_1_i0} -quiet] -quiet

# IP: c:/Users/dell/Desktop/PFA_PROJET_FINAL/project_FIR-final/project_FIR-final.srcs/sources_1/ip/lab1_4_2_sol_0/lab1_4_2_sol_floating_point_v7_1_i1/lab1_4_2_sol_floating_point_v7_1_i1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==lab1_4_2_sol_floating_point_v7_1_i1 || ORIG_REF_NAME==lab1_4_2_sol_floating_point_v7_1_i1} -quiet] -quiet

# XDC: c:/Users/dell/Desktop/PFA_PROJET_FINAL/project_FIR-final/project_FIR-final.srcs/sources_1/ip/lab1_4_2_sol_0/constrs/lab1_4_2_sol.xdc
# XDC: The top module name and the constraint reference have the same name: 'lab1_4_2_sol_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: c:/Users/dell/Desktop/PFA_PROJET_FINAL/project_FIR-final/project_FIR-final.srcs/sources_1/ip/lab1_4_2_sol_0/lab1_4_2_sol_0.xci
# IP: The module: 'lab1_4_2_sol_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: c:/Users/dell/Desktop/PFA_PROJET_FINAL/project_FIR-final/project_FIR-final.srcs/sources_1/ip/lab1_4_2_sol_0/lab1_4_2_sol_floating_point_v7_1_i0/lab1_4_2_sol_floating_point_v7_1_i0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==lab1_4_2_sol_floating_point_v7_1_i0 || ORIG_REF_NAME==lab1_4_2_sol_floating_point_v7_1_i0} -quiet] -quiet

# IP: c:/Users/dell/Desktop/PFA_PROJET_FINAL/project_FIR-final/project_FIR-final.srcs/sources_1/ip/lab1_4_2_sol_0/lab1_4_2_sol_floating_point_v7_1_i1/lab1_4_2_sol_floating_point_v7_1_i1.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==lab1_4_2_sol_floating_point_v7_1_i1 || ORIG_REF_NAME==lab1_4_2_sol_floating_point_v7_1_i1} -quiet] -quiet

# XDC: c:/Users/dell/Desktop/PFA_PROJET_FINAL/project_FIR-final/project_FIR-final.srcs/sources_1/ip/lab1_4_2_sol_0/constrs/lab1_4_2_sol.xdc
# XDC: The top module name and the constraint reference have the same name: 'lab1_4_2_sol_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
