# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/moham/OneDrive/Bureau/ug948-design-files/ip_catalog/cic.srcs/sources_1/bd/cic_bd/ip/cic_bd_rst_processing_system_1_50M_0/cic_bd_rst_processing_system_1_50M_0.xci
# IP: The module: 'cic_bd_rst_processing_system_1_50M_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/moham/OneDrive/Bureau/ug948-design-files/ip_catalog/cic.srcs/sources_1/bd/cic_bd/ip/cic_bd_rst_processing_system_1_50M_0/cic_bd_rst_processing_system_1_50M_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'cic_bd_rst_processing_system_1_50M_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: c:/Users/moham/OneDrive/Bureau/ug948-design-files/ip_catalog/cic.srcs/sources_1/bd/cic_bd/ip/cic_bd_rst_processing_system_1_50M_0/cic_bd_rst_processing_system_1_50M_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'cic_bd_rst_processing_system_1_50M_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: c:/Users/moham/OneDrive/Bureau/ug948-design-files/ip_catalog/cic.srcs/sources_1/bd/cic_bd/ip/cic_bd_rst_processing_system_1_50M_0/cic_bd_rst_processing_system_1_50M_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'cic_bd_rst_processing_system_1_50M_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: c:/Users/moham/OneDrive/Bureau/ug948-design-files/ip_catalog/cic.srcs/sources_1/bd/cic_bd/ip/cic_bd_rst_processing_system_1_50M_0/cic_bd_rst_processing_system_1_50M_0.xci
# IP: The module: 'cic_bd_rst_processing_system_1_50M_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/moham/OneDrive/Bureau/ug948-design-files/ip_catalog/cic.srcs/sources_1/bd/cic_bd/ip/cic_bd_rst_processing_system_1_50M_0/cic_bd_rst_processing_system_1_50M_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'cic_bd_rst_processing_system_1_50M_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: c:/Users/moham/OneDrive/Bureau/ug948-design-files/ip_catalog/cic.srcs/sources_1/bd/cic_bd/ip/cic_bd_rst_processing_system_1_50M_0/cic_bd_rst_processing_system_1_50M_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'cic_bd_rst_processing_system_1_50M_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: c:/Users/moham/OneDrive/Bureau/ug948-design-files/ip_catalog/cic.srcs/sources_1/bd/cic_bd/ip/cic_bd_rst_processing_system_1_50M_0/cic_bd_rst_processing_system_1_50M_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'cic_bd_rst_processing_system_1_50M_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
